# Generated by Django 5.2.8 on 2025-12-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='station',
            name='positions',
        ),
        migrations.CreateModel(
            name='StationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_line', to='tickets.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_station', to='tickets.station')),
            ],
        ),
    ]
