# Generated by Django 5.2.8 on 2025-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_line_remove_station_lines_remove_station_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='direction',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='direction',
            field=models.JSONField(default=list),
        ),
    ]
