# Generated by Django 5.2.8 on 2025-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_purchaserequest_direction_ticket_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
