# Generated by Django 5.2.8 on 2025-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_line_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
